# ref: https://github.com/actions/runner-images
name: amd64 MacOS Bazel

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        bazel: [
          {compilation_mode: opt},
          {compilation_mode: dbg},
        ]
        cpp: [
          #{version: 14, flags: "-std=c++14"},
          {version: 17, flags: "-std=c++17"},
          #{version: 20, flags: "-std=c++20"},
        ]
        exclude:
          # only test `-c dbg` build with C++17
          - cpp: {version: 14}
            bazel: {compilation_mode: dbg}
          - cpp: {version: 20}
            bazel: {compilation_mode: dbg}
      fail-fast: false
    name: MacOS•Bazel(${{ matrix.bazel.compilation_mode }},C++${{ matrix.cpp.version }})
    runs-on: macos-13 # last macos intel based runner
    steps:
      - uses: actions/checkout@v4
      - name: Set Java to OpenJDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c ${{ matrix.bazel.compilation_mode }}
          --cxxopt=${{ matrix.cpp.flags }} --host_cxxopt=${{ matrix.cpp.flags }}
          --subcommands=pretty_print
          --enable_bzlmod
          //...
      - name: Test
        run: >
          bazel test
          -c ${{ matrix.bazel.compilation_mode }}
          --cxxopt=${{ matrix.cpp.flags }} --host_cxxopt=${{ matrix.cpp.flags }}
          --subcommands=pretty_print
          --enable_bzlmod
          //...

  amd64_macos_bazel:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v4
